name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0"

      # If wrapper exists, use it; else fall back to `gradle`
      - name: Build Debug APK (wrapper if present)
        run: |
          if [ -f "./gradlew" ]; then
            chmod +x gradlew
            ./gradlew :app:assembleDebug --stacktrace --info
          else
            echo "Gradle wrapper not found; using system gradle"
            gradle :app:assembleDebug --stacktrace --info
          fi

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk