
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17 (Temurin) + Gradle cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # --- RUTA A: si el repo tiene wrapper (gradlew) lo usamos
      - name: Make gradlew executable
        if: ${{ hashFiles('gradlew') != '' }}
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        if: ${{ hashFiles('gradlew') != '' }}
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug --stacktrace --info

      # --- RUTA B: si NO hay wrapper, usa Gradle 8.5 standalone
      - name: Set up Gradle 8.5 (no wrapper)
        if: ${{ hashFiles('gradlew') == '' }}
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: Build with Gradle 8.5 (no wrapper)
        if: ${{ hashFiles('gradlew') == '' }}
        run: gradle assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
