name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Instala SDK de Android y acepta licencias
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Prepara Gradle (sin necesitar ./gradlew en el repo)
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      # Compilar APK de debug
      - name: Build Debug APK
        run: gradle assembleDebug --stacktrace

      # Subir APK para descargarlo como artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

